import counts from '@/data/counts.json';

/**
 * Per-category photo counts, safe to import from client components.
 *
 * Regenerated by scripts/derive-images.mjs alongside photos.json. Kept separate from
 * photos.json on purpose: that file carries a blur data URI per photo and is ~60KB, and
 * the header only needs seven integers.
 */
const map = counts as Record<string, number>;

export const countFor = (slug: string): number => map[slug] ?? 0;
export const totalCount = (): number => map.total ?? 0;
